### ISSUE TITLE
NDC19.2 API Endpoint not working

### ISSUE THREAD

**Issue by ericfan** [airtechzone/ndc-192-postman-collection#1]
@tdurivaux @vsanvincenti 

Would you mind take a look at the NDC 19.2 Endpoint(http://iata.api.mashery.com/athena/ndc192api
)? It's not working now

I always get gateway error
```html
<h1>Gateway Timeout</h1>
```

**Comment by tdurivaux** [comment]
There is ongoing maintenance, it should be back up and running very soon.

**Comment by tdurivaux** [comment]
The sandbox is up and running again.
